[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["pip install -r papermind/requirements.txt"]

[phases.build]
cmds = ["echo 'Build completed - dependencies installed'"]

[start]
cmd = "cd papermind/backend && python start_production.py"
